### ISSUE TITLE
Suggest new test case to cover file extension capitalization

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#56]
Have some test case to cover that file names and extension are case insensitive. For example no test case with extension *.PNG in uppercase.

**Comment by JimZuber** [comment]
@jordig100  - I am looking at issue #56 on Github and you suggested in this issue that we have a test case that covers filenames and extensions as being case insensitive.

Looking at the test suite, we have several test cases that verify that content type definitions are case insensitive, both the default extension and the PartName in an override. I do not specifically test PNG or JPG, but test "model" with capitalization variations. I think this is adequate.

However, I wonder if the issue you were concerned about is a difference between the capitalization in a relationship target attribute and the capitalization of the stored part name or path. 

The OPC specification is very confusing when it comes to capitalization. For instance...

-Section 9.1.1.3.2 states "Part URI equivalence is determined by comparing part URIs as case-insensitive ASCII strings." 

-Section 10.2.2 states "ZIP item names are case-sensitive ASCII strings."

-Section 13.2.4.24 states " Producers and consumers shall compare values as case-sensitive Unicode strings" with respect to relationship transforms

-There is also discussion in the OPC specification about the differences in capitalization sensitivity between windows and linux as it related to unzipping content

When developing the first test suite for HP I struggled with this ambiguity and decided to make sure all the relationship targets and zip file names aligned from a capitalization perspective in the  test suite. However, I did not define a negative test case where the relationship target had one capitalization and the zip file a different capitalization. I cannot remember whether this omission was deliberate or accidental.

Most 3MF implementation treat relationship targets as case sensitive with the exception of Microsoft's 3D Builder and Paint 3D utilities.

So, if we are confident that the OPC relationship targets should be treated as case sensitive (I think they should be), then what is missing in the test suite is a negative test case that expects the consumer to reject a mismatch in capitalization for a relationship target and the associated part name.

Let me know what you think.

**Comment by JimZuber** [comment]
Suites 1 – 6
•	Added negative test case N_???_0204_02 - Test where the capitalization of the thumbnail extension zip part name differs from the capitalization used in the relationship Target attribute

Will close issue when current update is complete and files are moved to Github.

**Comment by JimZuber** [comment]
Corrected files have been moved to the develop branch

**Comment by JimZuber** [comment]
Version 2.0.0 of the test_suite has been approved. The fixes to this issue will be merged with the Master branch and released. Closing this issue.
