### ISSUE TITLE
P_XXX_0104_03 should not be officially supported

### ISSUE THREAD

**Issue by qmuntal** [3MFConsortium/test_suites#62]
**Case P_XXX_0104_03 description**

> Create 3MF file with model part root names that use a UTF-8 Unicode character from outside the standard ASCII character set, excluding symbols (use Windows charmap.exe).
Conformance ID: M1.17, M3.2, O1.4, M2.12

The root name used for this case is `Ԫ3dmodel.model`.

**Context**

The rule M3.2 says:

> ZIP item names are case-sensitive ASCII strings. Package implementers shall create ZIP item names that conform to ZIP archive file name grammar. 

The file name grammar is defined as follows:

> part-URI = 1*( "/" segment )
segment = 1*( pchar )
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded = "%" HEXDIG HEXDIG
sub-delims = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

**Issue**

The character `Ԫ` is not an ASCII character, therefore it cannot be used in a part name unless it is properly pct-encoded as `%D4%AA`.

This test case is forcing 3MF consumers to support more cases than required by the spec.

**Comment by JimZuber** [comment]
This test case embeds a unicode character in a part name. The OPC spec says the following....

Section 9.1.1.1 - [Note: Not all versions of the ZIP specification support a Part name represented as a Part IRI. To preserve interoperability, implementers are encouraged to use the currently more prevalent Part URI representation. end note]  <This infers that the part name could be either a unicode string (IRI) or a ASCII with escaped characters for unicode (URI)>

10.2.2 - ZIP item names are case-sensitive ASCII strings. Package implementers shall create ZIP item names that conform to ZIP archive file name grammar.  <This infers that the file name must be ASCII with escaped characters for unicode> 

So 3 choices:

1)Leave test case as is with part name "/3D/Ԫ3dmodel.model"

2)Modify the test case with part name as "/3D/%D4%AA3dmodel.model"

3)Add an additional test case with the escaped version in addition to item 1

3)Delete test case

As a side note, most 3MF implementations support the IRI syntax in item 1 above,  but Microsoft's Paint 3D is not happy unless the syntax in item 2 is used.

Thoughts

**Comment by qmuntal** [comment]
This is a good summary @JimZuber. I agree that the spec says that a part names can contain Unicode strings in its IRI representation, but the chapter 12.2.2 specify that a part name must be mapped to a case-sensitive ASCII string when creating the physical representation of the part.

So my interpretation is that one can use Unicode strings one relationships and any logical manipulation, but once serialized these string must be percentage-encoded.

**Comment by JimZuber** [comment]
@qmuntal , that is a helpful clarification. 

So, what if we had a test case where the relationship target used unicode, but the zip file part name used escape encoding. I just tried this scenario on four 3MF implementations with the root model file using a unicode character and the zip file part name escape encoded. Three of the  implementations where unhappy as they could not find the root model file. However Microsoft's 3D Builder utility application had no problem with this scenario. This leads me to beleive that a test case as suggested would be valid and would help other implementers improve their handling of these character mapping transforms.

**Comment by jordig100** [comment]
I understant that the proposal is to create a negative test case for the unicode in the ZIP part name and a positive test case using the escape chars, while in the .rel file still use unicode.
Would it be any backwards compatibility issue with major apps? What do they generate in this situation?

**Comment by qmuntal** [comment]
@jordig100 what I´m proposing here is not to explicitly forbid to support unicode strings in ZIP part names, just to remove this test case from the official test suite, as it is something that goes against the OPC spec and it should not be mandatory to implement. 

Then the conversation with @JimZuber have derived to another proposals: Create a test case to verify that a 3mf consumer can read packages with unicode relationships but escape part names.

And I would add yet another test case: 3mf creators shall create ZIP files that conform to the logical item name as defined in the OPC spec, even if the inputs contain unicode strings. Notice that this test case does not force to break backwards compatibility, and 3mf consumers can still support unicode strings in ZIP files.

**Comment by JimZuber** [comment]
@qmuntal I am a little fuzzy on what the second test case you suggested would look like. Would there be escaped characters in the relationships as well as in the zip file names?

**Comment by qmuntal** [comment]
I mean that the physical zip part names should always be created in its escaped, even if the part name contains unicode strings, and  relationships should use whatever encoding the 3mf creator decides to use (IRI, URI, ...).

**Comment by JimZuber** [comment]
Capturing @jordig100 test case suggestions for this issue...

-Additional test case so the part name in the ZIP is "/3D/%D4%AA3dmodel.model“, while still referencing it in the xml as Unicode.

-Additional test cases for textures images as IRI and URI.

**Comment by jordig100** [comment]
The test file (P_XXX_0104_03) as it is should be a negative test case, according to the spec. Since neither the ZIP part name nor the relationship xml could contain not ASCII characters, as defined in anyURI.
Suggest to add a second negative test case for the texture files in Unicode in both the ZIP part name and in xml (relationship) and texture2d.
Add two positive test cases so both previous cases (model name and texture2d) are defined with escaped sequences as ASCII: "%D4%AA" instead of unicode "Ԫ".
Include in the tests that the object's name and partnumber have an unicode string.

**Comment by JimZuber** [comment]
Suites 1 – 6
•	Moved positive test case P_???_104_03 to a negative test case  N_???_208_01 
•	Deleted positive 104_03
•	Added new positive test case P_???_104_04 – Model name and related relationship referenced using escaped Unicode characters. Include part name and part number with unescaped Unicode

Suites 2 and 6
•	New negative test case N_???_208_02 - Added negative test case for the texture files using unescaped Unicode in the ZIP part name, xml (relationship), and texture2d portion of model.
•	Add new positive test case P_???_104_05 – Added positive test for the texture files using escaped Unicode in the ZIP part name, xml (relationship), and texture2d portion of model.


Will close issue when current update is complete and files are moved to Github.

**Comment by JimZuber** [comment]
Corrected files have been moved to the develop branch

**Comment by JimZuber** [comment]
Version 2.0.0 of the test_suite has been approved. The fixes to this issue will be merged with the Master branch and released. Closing this issue.
