### ISSUE TITLE
Missing test case for defined pid but not property indexes

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#65]
Test "P_???_0502 Triangle P1, 2, 3 Usage" does not cover the case where pid is defined but no p1 is defined.
The expected result is to apply the default object property.

**Comment by JimZuber** [comment]
To clarify, we need to add the following test cases for triangles, beamlattice, beams, and Balls as follows:

pid present, no index  (i.e. p1) - use default
index present, no pid. - index applied to default pid

The existing test cases for triangles, beamlattice, and beams have BOTH pid and the index present in override test cases.

**Comment by JimZuber** [comment]
-Test Specification was updated to add tests for this functionality.
-Test case P_???_0312_01 was updated to test missing functionality described in this issue on suites 1, 3, 4, and 5
-Test case P_???_0506_01 was updated to test missing functionality described in this issue on suites 2 and 5
-Expected thumbnail albums updated for suites 1 to 6
