### ISSUE TITLE
Beamlattice balls tests using the new version of the namespace

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#68]
Beamlatice balls will be redefined with a new version of the namespace. See issue: https://github.com/3MFConsortium/spec_beamlattice/issues/37

Current test cases need to be updated using the new version of the namespace for ball, while still using the first version of the name space for the base lattices.

Provide some tests with combinations of the two versions as required and optional.

**Comment by JimZuber** [comment]
So, just to confirm, we will need to do the following:

1)For all current test cases that use balls, add a new namespace for balls and add that namespace as a required extension

2)Have one new positive test case that contains both balls and the new namespace, but where the balls are NOT a required extension. Would need to have two expected results images, with and without balls

3)A negative test case that contains balls and does NOT contain the new namespace mapping.

**Comment by jordig100** [comment]
The test case 3) is good to have. However we expect most implementations do not reject the file, just to ignore the balls element. They might provide instead a warning, or just silently ignore it.

**Comment by JimZuber** [comment]
This has been completed, all positive and negative test cases that use balls have been revised to use new ball schema. Two new test cases added:

P_BXX_2021_09 - Illustrate use of ballref in a beamset
P_BXX_2021_10 -  Test case that contains balls, but the ball schema is not a required extension

Will close issue when current update is complete and files are moved to Github.

**Comment by JimZuber** [comment]
Corrected files have been moved to the develop branch

**Comment by JimZuber** [comment]
Version 2.0.0 of the test_suite has been approved. The fixes to this issue will be merged with the Master branch and released. Closing this issue.
