### ISSUE TITLE
3mfEditor reports warnings when only one property in triangle.

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#77]
When triangles only define one property in P1, the 3mfEditor reports the warning:

WR_015: Triangle: with pid=2 in file: /3D/3dmodel.model has not defined p2.

Since this is a valid case, and extensively used in many 3MF, this would cause to stop checking the 3MF after the maximum. Even if we increase the maximum, the log would be filled up with warnings.

I think better to just ignore this case, and do not report a warning.

**Comment by JimZuber** [comment]
Warnings are now suppressed if only a P1 is specified on the triangle. Will close this  issue once an updated 3MF Editor jar and source are posted to the github site.

**Comment by JimZuber** [comment]
Jar Updated

**Comment by JimZuber** [comment]
Jar updated

**Comment by JimZuber** [comment]
Jar updated
