### ISSUE TITLE
3mfEditor do not report as error some negatives alternatives files

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#78]
Files: N_XPX_0822_01, N_XPX_0822_02, N_XPX_0822_03 and N_XPX_0822_04 are reported as correct by the 3mfEditor.
But they seem the match the description in the test suite, so they should be rejected.

**Comment by JimZuber** [comment]
All the negative test cases noted now generate an error message when validated by the 3MF Editor. Specifically, this is the list of issues in the test cases that are now being validated by the 3MF Editor....

N_XPX_O822 – Production Alternatives Miscellaneous Errors
01 – Root model object specifying an alternative (also in the root model) that itself has alternatives
02 – Root model object with alternatives, whose alternatives point to a non root model component that itself has alternatives
03  - Duplicate UUID value in alternative attribute
04 – Create a scenario where the first alternative is a fullres mesh object, but is positioned in the model after the primary object and its related alternatives. This should generate an exception as the printer will encounter the reference to the first alternative before it's mesh has been defined.

Will close this issue when when and update 3MF Editor jar and source code are posted to the github site.

**Comment by JimZuber** [comment]
Validations have been added
