### ISSUE TITLE
Displacement 3MF Editor validation Issues

### ISSUE THREAD

**Issue by JimZuber** [3MFConsortium/test_suites#95]
Using this issue to capture 3MF Editor Validation Errors some that we can accumulate them and make one fix rather than dealing with them on a on-off basis when is much more time consuming.....

1)Incorrect error message when finding an invalid did attribute value in a triangle or specified as a default in triangles 
Current:      "ER_151: triangle with did 24 points to a non-existant displacement2d resource". 
Should Be:  "ER_151: triangle with did 24 points to a non-existent disp2dgroup resource"
and..
Current:  ER_149: triangles with did 99 points to a non-existant displacement2d resource
Should be: ER_149: triangles with did 99 points to a non-existent disp2dgroup resource

2)The work "existent" is misspelled in a number of error messages as "existant"

3)The validator ignores the  did, d1, d2, d3, or d4 subements of triangle if it contains a namespace prefix (which it may or may not have). As a result we do not catch invalid did values or incorrect indexes if the namespace is present.

4)The check for scalar factor currently generates an error if it is less that zero. The correct criteria for failure should be zero or less and the error message should be revised as follows....  

ER_175: Scalar product of xyz values for vertex (1.0, 0.5180606761608713, 1.0) and normvector (0.0, -1.0, 0.0) is zero or a negative value.
Object 4 triangle index 10, scalar values pointed to by v1 and d1

**Comment by JimZuber** [comment]
A few additional items noticed what generating negative test cases....

-The editor did not appear to complain if the index for "n" in disp2dcoord what only off by 1. More than 1, you get an error message. We should also check other indices related to displacements for the same error.

-Many error types that involve incorrect references to vertices, triangles, displacement indices, and norm vectors also generate false errors related to scalar factor. I am guessing that the values used for calculating the scalar factor are initialized with zero, and when another error occurs that prevents these default values from being updated, the scalar factor calculation runs with the zero values resulting in false errors. Once fixed, we should go through all the negative test cases for displacements to validate these false errors do not occur.

**Comment by JimZuber** [comment]
Note that item 4 on the initial post (not treating 0 as an error in scalar factor) has been corrected and is implemented in the version of the editor available on github.

**Comment by JimZuber** [comment]
One more validation error that should be updated...

When the ContentType attribute enumeration in displacement2d inconsistent with type of file pointed to with path, the editor does not flag this as an error. I think that the editor knows internally whether the file types are png or jpg (irrespective of file name extension), so this should be a simple validation to add to the editor.

**Comment by JimZuber** [comment]
One more error that needs to be fixed. THere appears to be an incorrect scalar product calculation in some narrow situations. There scenarios using the attached file...

Valid scalar product error
        <d:normvectorgroup id="5">
            <d:normvector x="0" y="-1" z="0"/>
            <d:normvector x="0" y="0" z="1"/>
        </d:normvectorgroup>
ER_175: Scalar product (-0.0024333769596208664) of normal vector **(0.46947287068482696, 0.8829435442696889, -0.0024333769596208664)** and normvector (0.0, 0.0, 1.0) is 0 or less. Normal vector from Object 11 triangle index 2 , displacement normvector from d1

Note the values for normal vector which should be independent of normvector.

Invalid error...
        <d:normvectorgroup id="5">
            <d:normvector x="0" y="-1" z="0"/>
            <d:normvector x="0.70710678" y="0.70710678" z="0"/>
        </d:normvectorgroup>
ER_175: Scalar product (0.0) of normal vector **(0.0, 0.0, 1.0)** and normvector (0.70710678, 0.70710678, 0.0) is 0 or less. Normal vector from Object 11 triangle index 3 , displacement normvector from d1

The value of normal vector should be identical to the prior example, but it isn't. Validating the correct normal vector value with the normvector in this example results in a valid scalar factor.

Finally, just to close the loop, the following norm vector values result in a successful validation....

        <d:normvectorgroup id="5">
            <d:normvector x="0" y="-1" z="0"/>
            <d:normvector x="0.70710678" y="0" z="0.70710678"/>
        </d:normvectorgroup>

No structural errors found in C:/temp/2-12-24-update/2-12-24-update/P_DPX_3218_01/P_DPX_3218_01.3mf 

 
[P_DPX_3218_01.zip](https://github.com/3MFConsortium/test_suites/files/14271293/P_DPX_3218_01.zip)

**Comment by JimZuber** [comment]
Change Error 133 "normvector whose module is less than 1" to a warning so that it can be disabled.

**Comment by jordig100** [comment]
I would say normvector above or below 1.

**Comment by JimZuber** [comment]
3MF validation incorrectly complains about a path being in displacement2d of the model file is a non-root model files. See test 3224_01

**Comment by JimZuber** [comment]
Validations or fixes have been implemented in the 3MF Editor that address all of the gaps outlined in this issue
